### ISSUE TITLE
Expected date for code and dataset release?

### ISSUE THREAD

**Issue by culture4515** [yyang181/BiSTNet#1]
Do you have expected date for code and dataset release?

**Comment by yyang181** [comment]
Sorry for the late response. The testing code and colorization results (https://github.com/yyang181/NTIRE23-VIDEO-COLORIZATION) related to NTIRE2023 Video Colorization Challenge have been released. Please check our updated readme.md. Due to copyright protection issues from our collaborating company, we are unable to provide the training codes and related data of our method at this time. We apologize for any inconvenience.
